# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _ButtonWrapper
else:
    import _ButtonWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ButtonWrapper.delete_SwigPyIterator

    def value(self):
        return _ButtonWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ButtonWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ButtonWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ButtonWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ButtonWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ButtonWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _ButtonWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _ButtonWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _ButtonWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ButtonWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ButtonWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ButtonWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ButtonWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ButtonWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ButtonWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ButtonWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ButtonWrapper:
_ButtonWrapper.SwigPyIterator_swigregister(SwigPyIterator)
import fastdds
class _ButtonSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ButtonWrapper.delete__ButtonSeq

# Register _ButtonSeq in _ButtonWrapper:
_ButtonWrapper._ButtonSeq_swigregister(_ButtonSeq)
class ButtonSeq(_ButtonSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _ButtonWrapper.delete_ButtonSeq

    def __init__(self, *args):
        _ButtonWrapper.ButtonSeq_swiginit(self, _ButtonWrapper.new_ButtonSeq(*args))

    def __len__(self):
        return _ButtonWrapper.ButtonSeq___len__(self)

    def __getitem__(self, i):
        return _ButtonWrapper.ButtonSeq___getitem__(self, i)

# Register ButtonSeq in _ButtonWrapper:
_ButtonWrapper.ButtonSeq_swigregister(ButtonSeq)
class Button(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _ButtonWrapper.delete_Button

    def __init__(self, *args):
        _ButtonWrapper.Button_swiginit(self, _ButtonWrapper.new_Button(*args))

    def __eq__(self, x):
        return _ButtonWrapper.Button___eq__(self, x)

    def __ne__(self, x):
        return _ButtonWrapper.Button___ne__(self, x)

    def index(self, *args):
        return _ButtonWrapper.Button_index(self, *args)

    def button(self, *args):
        return _ButtonWrapper.Button_button(self, *args)

    @staticmethod
    def getMaxCdrSerializedSize(current_alignment=0):
        return _ButtonWrapper.Button_getMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def getCdrSerializedSize(data, current_alignment=0):
        return _ButtonWrapper.Button_getCdrSerializedSize(data, current_alignment)

    def serialize(self, cdr):
        return _ButtonWrapper.Button_serialize(self, cdr)

    def deserialize(self, cdr):
        return _ButtonWrapper.Button_deserialize(self, cdr)

    @staticmethod
    def getKeyMaxCdrSerializedSize(current_alignment=0):
        return _ButtonWrapper.Button_getKeyMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def isKeyDefined():
        return _ButtonWrapper.Button_isKeyDefined()

    def serializeKey(self, cdr):
        return _ButtonWrapper.Button_serializeKey(self, cdr)

# Register Button in _ButtonWrapper:
_ButtonWrapper.Button_swigregister(Button)
GEN_API_VER = _ButtonWrapper.GEN_API_VER
class ButtonPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _ButtonWrapper.ButtonPubSubType_swiginit(self, _ButtonWrapper.new_ButtonPubSubType())
    __swig_destroy__ = _ButtonWrapper.delete_ButtonPubSubType

    def serialize(self, data, payload):
        return _ButtonWrapper.ButtonPubSubType_serialize(self, data, payload)

    def deserialize(self, payload, data):
        return _ButtonWrapper.ButtonPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, data):
        return _ButtonWrapper.ButtonPubSubType_getSerializedSizeProvider(self, data)

    def getKey(self, data, ihandle, force_md5=False):
        return _ButtonWrapper.ButtonPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _ButtonWrapper.ButtonPubSubType_createData(self)

    def deleteData(self, data):
        return _ButtonWrapper.ButtonPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _ButtonWrapper.ButtonPubSubType_is_bounded(self)

    def is_plain(self):
        return _ButtonWrapper.ButtonPubSubType_is_plain(self)

    def construct_sample(self, memory):
        return _ButtonWrapper.ButtonPubSubType_construct_sample(self, memory)
    m_md5 = property(_ButtonWrapper.ButtonPubSubType_m_md5_get, _ButtonWrapper.ButtonPubSubType_m_md5_set)
    m_keyBuffer = property(_ButtonWrapper.ButtonPubSubType_m_keyBuffer_get, _ButtonWrapper.ButtonPubSubType_m_keyBuffer_set)

# Register ButtonPubSubType in _ButtonWrapper:
_ButtonWrapper.ButtonPubSubType_swigregister(ButtonPubSubType)

