# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

import fastdds
from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _FuelWrapper
else:
    import _FuelWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError(
                "You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _FuelWrapper.delete_SwigPyIterator

    def value(self):
        return _FuelWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _FuelWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _FuelWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _FuelWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _FuelWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _FuelWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _FuelWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _FuelWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _FuelWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _FuelWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _FuelWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _FuelWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _FuelWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _FuelWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _FuelWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _FuelWrapper.SwigPyIterator___sub__(self, *args)

    def __iter__(self):
        return self


# Register SwigPyIterator in _FuelWrapper:
_FuelWrapper.SwigPyIterator_swigregister(SwigPyIterator)


class _FuelSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _FuelWrapper.delete__FuelSeq


# Register _FuelSeq in _FuelWrapper:
_FuelWrapper._FuelSeq_swigregister(_FuelSeq)


class FuelSeq(_FuelSeq):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _FuelWrapper.delete_FuelSeq

    def __init__(self, *args):
        _FuelWrapper.FuelSeq_swiginit(self, _FuelWrapper.new_FuelSeq(*args))

    def __len__(self):
        return _FuelWrapper.FuelSeq___len__(self)

    def __getitem__(self, i):
        return _FuelWrapper.FuelSeq___getitem__(self, i)


# Register FuelSeq in _FuelWrapper:
_FuelWrapper.FuelSeq_swigregister(FuelSeq)


class Fuel(object):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _FuelWrapper.delete_Fuel

    def __init__(self, *args):
        _FuelWrapper.Fuel_swiginit(self, _FuelWrapper.new_Fuel(*args))

    def __eq__(self, x):
        return _FuelWrapper.Fuel___eq__(self, x)

    def __ne__(self, x):
        return _FuelWrapper.Fuel___ne__(self, x)

    def index(self, *args):
        return _FuelWrapper.Fuel_index(self, *args)

    def litersRemaining(self, *args):
        return _FuelWrapper.Fuel_litersRemaining(self, *args)

    def litersSpent(self, *args):
        return _FuelWrapper.Fuel_litersSpent(self, *args)

    @staticmethod
    def getMaxCdrSerializedSize(current_alignment=0):
        return _FuelWrapper.Fuel_getMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def getCdrSerializedSize(data, current_alignment=0):
        return _FuelWrapper.Fuel_getCdrSerializedSize(data, current_alignment)

    def serialize(self, cdr):
        return _FuelWrapper.Fuel_serialize(self, cdr)

    def deserialize(self, cdr):
        return _FuelWrapper.Fuel_deserialize(self, cdr)

    @staticmethod
    def getKeyMaxCdrSerializedSize(current_alignment=0):
        return _FuelWrapper.Fuel_getKeyMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def isKeyDefined():
        return _FuelWrapper.Fuel_isKeyDefined()

    def serializeKey(self, cdr):
        return _FuelWrapper.Fuel_serializeKey(self, cdr)


# Register Fuel in _FuelWrapper:
_FuelWrapper.Fuel_swigregister(Fuel)
GEN_API_VER = _FuelWrapper.GEN_API_VER


class FuelPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _FuelWrapper.FuelPubSubType_swiginit(
            self, _FuelWrapper.new_FuelPubSubType())
    __swig_destroy__ = _FuelWrapper.delete_FuelPubSubType

    def serialize(self, data, payload):
        return _FuelWrapper.FuelPubSubType_serialize(self, data, payload)

    def deserialize(self, payload, data):
        return _FuelWrapper.FuelPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, data):
        return _FuelWrapper.FuelPubSubType_getSerializedSizeProvider(self, data)

    def getKey(self, data, ihandle, force_md5=False):
        return _FuelWrapper.FuelPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _FuelWrapper.FuelPubSubType_createData(self)

    def deleteData(self, data):
        return _FuelWrapper.FuelPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _FuelWrapper.FuelPubSubType_is_bounded(self)

    def is_plain(self):
        return _FuelWrapper.FuelPubSubType_is_plain(self)

    def construct_sample(self, memory):
        return _FuelWrapper.FuelPubSubType_construct_sample(self, memory)
    m_md5 = property(_FuelWrapper.FuelPubSubType_m_md5_get,
                     _FuelWrapper.FuelPubSubType_m_md5_set)
    m_keyBuffer = property(_FuelWrapper.FuelPubSubType_m_keyBuffer_get,
                           _FuelWrapper.FuelPubSubType_m_keyBuffer_set)


# Register FuelPubSubType in _FuelWrapper:
_FuelWrapper.FuelPubSubType_swigregister(FuelPubSubType)
