// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
<<<<<<< HEAD
 * @file LowFuelAlert.cpp
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
 * @file MpG.cpp
=======
 * @file LowFuelAlert.cpp
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

<<<<<<< HEAD
#include "LowFuelAlert.h"
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
#include "MpG.h"
=======
#include "LowFuelAlert.h"
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
MpG::MpG()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7fac631b
    m_index = 0;
    // m_mpg com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5b87ed94
    m_mpg = 0.0;

}

MpG::~MpG()
=======
>>>>>>> master
LowFuelAlert::LowFuelAlert()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2758fe70
    m_index = 0;
    // m_isFuelLow com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1f36e637
    m_isFuelLow = 0;

}

LowFuelAlert::~LowFuelAlert()
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
{


}

<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
MpG::MpG(
        const MpG& x)
{
    m_index = x.m_index;
    m_mpg = x.m_mpg;
}

MpG::MpG(
        MpG&& x)
{
    m_index = x.m_index;
    m_mpg = x.m_mpg;
}

MpG& MpG::operator =(
        const MpG& x)
{

    m_index = x.m_index;
    m_mpg = x.m_mpg;
=======
>>>>>>> master
LowFuelAlert::LowFuelAlert(
        const LowFuelAlert& x)
{
    m_index = x.m_index;
    m_isFuelLow = x.m_isFuelLow;
}

LowFuelAlert::LowFuelAlert(
        LowFuelAlert&& x)
{
    m_index = x.m_index;
    m_isFuelLow = x.m_isFuelLow;
}

LowFuelAlert& LowFuelAlert::operator =(
        const LowFuelAlert& x)
{

    m_index = x.m_index;
    m_isFuelLow = x.m_isFuelLow;
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master

    return *this;
}

<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
MpG& MpG::operator =(
        MpG&& x)
{

    m_index = x.m_index;
    m_mpg = x.m_mpg;
=======
>>>>>>> master
LowFuelAlert& LowFuelAlert::operator =(
        LowFuelAlert&& x)
{

    m_index = x.m_index;
    m_isFuelLow = x.m_isFuelLow;
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master

    return *this;
}

<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
bool MpG::operator ==(
        const MpG& x) const
{

    return (m_index == x.m_index && m_mpg == x.m_mpg);
}

bool MpG::operator !=(
        const MpG& x) const
=======
>>>>>>> master
bool LowFuelAlert::operator ==(
        const LowFuelAlert& x) const
{

    return (m_index == x.m_index && m_isFuelLow == x.m_isFuelLow);
}

bool LowFuelAlert::operator !=(
        const LowFuelAlert& x) const
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
{
    return !(*this == x);
}

<<<<<<< HEAD
size_t LowFuelAlert::getMaxCdrSerializedSize(
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
size_t MpG::getMaxCdrSerializedSize(
=======
size_t LowFuelAlert::getMaxCdrSerializedSize(
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


<<<<<<< HEAD
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);
=======
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master



    return current_alignment - initial_alignment;
}

<<<<<<< HEAD
size_t LowFuelAlert::getCdrSerializedSize(
        const LowFuelAlert& data,
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
size_t MpG::getCdrSerializedSize(
        const MpG& data,
=======
size_t LowFuelAlert::getCdrSerializedSize(
        const LowFuelAlert& data,
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


<<<<<<< HEAD
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);
=======
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master



    return current_alignment - initial_alignment;
}

<<<<<<< HEAD
void LowFuelAlert::serialize(
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
void MpG::serialize(
=======
void LowFuelAlert::serialize(
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
    scdr << m_mpg;

}

void MpG::deserialize(
=======
>>>>>>> master
    scdr << m_isFuelLow;

}

void LowFuelAlert::deserialize(
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
<<<<<<< HEAD
    dcdr >> m_isFuelLow;
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
    dcdr >> m_mpg;
=======
    dcdr >> m_isFuelLow;
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
<<<<<<< HEAD
void LowFuelAlert::index(
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
void MpG::index(
=======
void LowFuelAlert::index(
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
<<<<<<< HEAD
uint32_t LowFuelAlert::index() const
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
uint32_t MpG::index() const
=======
uint32_t LowFuelAlert::index() const
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
<<<<<<< HEAD
uint32_t& LowFuelAlert::index()
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
uint32_t& MpG::index()
=======
uint32_t& LowFuelAlert::index()
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
{
    return m_index;
}

/*!
<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
 * @brief This function sets a value in member mpg
 * @param _mpg New value for member mpg
 */
void MpG::mpg(
        double _mpg)
{
    m_mpg = _mpg;
}

/*!
 * @brief This function returns the value of member mpg
 * @return Value of member mpg
 */
double MpG::mpg() const
{
    return m_mpg;
}

/*!
 * @brief This function returns a reference to member mpg
 * @return Reference to member mpg
 */
double& MpG::mpg()
{
    return m_mpg;
}


size_t MpG::getKeyMaxCdrSerializedSize(
=======
>>>>>>> master
 * @brief This function sets a value in member isFuelLow
 * @param _isFuelLow New value for member isFuelLow
 */
void LowFuelAlert::isFuelLow(
        int32_t _isFuelLow)
{
    m_isFuelLow = _isFuelLow;
}

/*!
 * @brief This function returns the value of member isFuelLow
 * @return Value of member isFuelLow
 */
int32_t LowFuelAlert::isFuelLow() const
{
    return m_isFuelLow;
}

/*!
 * @brief This function returns a reference to member isFuelLow
 * @return Reference to member isFuelLow
 */
int32_t& LowFuelAlert::isFuelLow()
{
    return m_isFuelLow;
}


size_t LowFuelAlert::getKeyMaxCdrSerializedSize(
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

<<<<<<< HEAD
bool LowFuelAlert::isKeyDefined()
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
bool MpG::isKeyDefined()
=======
bool LowFuelAlert::isKeyDefined()
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
{
    return false;
}

<<<<<<< HEAD
void LowFuelAlert::serializeKey(
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/MpG/MpG.cxx
void MpG::serializeKey(
=======
void LowFuelAlert::serializeKey(
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.cxx
>>>>>>> master
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
