# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

import fastdds
from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _LowFuelAlertWrapper
else:
    import _LowFuelAlertWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError(
                "You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LowFuelAlertWrapper.delete_SwigPyIterator

    def value(self):
        return _LowFuelAlertWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _LowFuelAlertWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _LowFuelAlertWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _LowFuelAlertWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _LowFuelAlertWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _LowFuelAlertWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _LowFuelAlertWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _LowFuelAlertWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _LowFuelAlertWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _LowFuelAlertWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _LowFuelAlertWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _LowFuelAlertWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _LowFuelAlertWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _LowFuelAlertWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _LowFuelAlertWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _LowFuelAlertWrapper.SwigPyIterator___sub__(self, *args)

    def __iter__(self):
        return self


# Register SwigPyIterator in _LowFuelAlertWrapper:
_LowFuelAlertWrapper.SwigPyIterator_swigregister(SwigPyIterator)


class _LowFuelAlertSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LowFuelAlertWrapper.delete__LowFuelAlertSeq


# Register _LowFuelAlertSeq in _LowFuelAlertWrapper:
_LowFuelAlertWrapper._LowFuelAlertSeq_swigregister(_LowFuelAlertSeq)


class LowFuelAlertSeq(_LowFuelAlertSeq):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LowFuelAlertWrapper.delete_LowFuelAlertSeq

    def __init__(self, *args):
        _LowFuelAlertWrapper.LowFuelAlertSeq_swiginit(
            self, _LowFuelAlertWrapper.new_LowFuelAlertSeq(*args))

    def __len__(self):
        return _LowFuelAlertWrapper.LowFuelAlertSeq___len__(self)

    def __getitem__(self, i):
        return _LowFuelAlertWrapper.LowFuelAlertSeq___getitem__(self, i)


# Register LowFuelAlertSeq in _LowFuelAlertWrapper:
_LowFuelAlertWrapper.LowFuelAlertSeq_swigregister(LowFuelAlertSeq)


class LowFuelAlert(object):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LowFuelAlertWrapper.delete_LowFuelAlert

    def __init__(self, *args):
        _LowFuelAlertWrapper.LowFuelAlert_swiginit(
            self, _LowFuelAlertWrapper.new_LowFuelAlert(*args))

    def __eq__(self, x):
        return _LowFuelAlertWrapper.LowFuelAlert___eq__(self, x)

    def __ne__(self, x):
        return _LowFuelAlertWrapper.LowFuelAlert___ne__(self, x)

    def index(self, *args):
        return _LowFuelAlertWrapper.LowFuelAlert_index(self, *args)

    def isFuelLow(self, *args):
        return _LowFuelAlertWrapper.LowFuelAlert_isFuelLow(self, *args)

    @staticmethod
    def getMaxCdrSerializedSize(current_alignment=0):
        return _LowFuelAlertWrapper.LowFuelAlert_getMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def getCdrSerializedSize(data, current_alignment=0):
        return _LowFuelAlertWrapper.LowFuelAlert_getCdrSerializedSize(data, current_alignment)

    def serialize(self, cdr):
        return _LowFuelAlertWrapper.LowFuelAlert_serialize(self, cdr)

    def deserialize(self, cdr):
        return _LowFuelAlertWrapper.LowFuelAlert_deserialize(self, cdr)

    @staticmethod
    def getKeyMaxCdrSerializedSize(current_alignment=0):
        return _LowFuelAlertWrapper.LowFuelAlert_getKeyMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def isKeyDefined():
        return _LowFuelAlertWrapper.LowFuelAlert_isKeyDefined()

    def serializeKey(self, cdr):
        return _LowFuelAlertWrapper.LowFuelAlert_serializeKey(self, cdr)


# Register LowFuelAlert in _LowFuelAlertWrapper:
_LowFuelAlertWrapper.LowFuelAlert_swigregister(LowFuelAlert)
GEN_API_VER = _LowFuelAlertWrapper.GEN_API_VER


class LowFuelAlertPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _LowFuelAlertWrapper.LowFuelAlertPubSubType_swiginit(
            self, _LowFuelAlertWrapper.new_LowFuelAlertPubSubType())
    __swig_destroy__ = _LowFuelAlertWrapper.delete_LowFuelAlertPubSubType

    def serialize(self, data, payload):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_serialize(self, data, payload)

    def deserialize(self, payload, data):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, data):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_getSerializedSizeProvider(self, data)

    def getKey(self, data, ihandle, force_md5=False):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_createData(self)

    def deleteData(self, data):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_is_bounded(self)

    def is_plain(self):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_is_plain(self)

    def construct_sample(self, memory):
        return _LowFuelAlertWrapper.LowFuelAlertPubSubType_construct_sample(self, memory)
    m_md5 = property(_LowFuelAlertWrapper.LowFuelAlertPubSubType_m_md5_get,
                     _LowFuelAlertWrapper.LowFuelAlertPubSubType_m_md5_set)
    m_keyBuffer = property(_LowFuelAlertWrapper.LowFuelAlertPubSubType_m_keyBuffer_get,
                           _LowFuelAlertWrapper.LowFuelAlertPubSubType_m_keyBuffer_set)


# Register LowFuelAlertPubSubType in _LowFuelAlertWrapper:
_LowFuelAlertWrapper.LowFuelAlertPubSubType_swigregister(
    LowFuelAlertPubSubType)
