// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
<<<<<<< HEAD
 * @file LowFuelAlert.i
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
 * @file Button.i
=======
 * @file LowFuelAlert.i
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

<<<<<<< HEAD
%module LowFuelAlert
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
%module Button
=======
%module LowFuelAlert
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master

// SWIG helper modules
%include "stdint.i"
%include "std_string.i"
%include "std_vector.i"
%include "std_array.i"
%include "std_map.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define RTPS_DllAPI
#define eProsima_user_DllExport


%{
<<<<<<< HEAD
#include "LowFuelAlert.h"
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
#include "Button.h"
=======
#include "LowFuelAlert.h"
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master

#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

////////////////////////////////////////////////////////
<<<<<<< HEAD
// Binding for class LowFuelAlert
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
// Binding for class Button
=======
// Binding for class LowFuelAlert
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
%ignore Button::Button(Button&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore Button::index(uint32_t&&);
=======
>>>>>>> master
%ignore LowFuelAlert::LowFuelAlert(LowFuelAlert&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore LowFuelAlert::index(uint32_t&&);
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
%ignore Button::index();
%rename("%s") Button::index() const;

%ignore Button::button(uint32_t&&);
=======
>>>>>>> master
%ignore LowFuelAlert::index();
%rename("%s") LowFuelAlert::index() const;

%ignore LowFuelAlert::isFuelLow(int32_t&&);
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
%ignore Button::button();
%rename("%s") Button::button() const;


%template(_ButtonSeq) eprosima::fastdds::dds::LoanableTypedCollection<Button, std::false_type>;
%template(ButtonSeq) eprosima::fastdds::dds::LoanableSequence<Button, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<Button, std::false_type>
=======
>>>>>>> master
%ignore LowFuelAlert::isFuelLow();
%rename("%s") LowFuelAlert::isFuelLow() const;


%template(_LowFuelAlertSeq) eprosima::fastdds::dds::LoanableTypedCollection<LowFuelAlert, std::false_type>;
%template(LowFuelAlertSeq) eprosima::fastdds::dds::LoanableSequence<LowFuelAlert, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<LowFuelAlert, std::false_type>
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master
{
    size_t __len__() const
    {
        return self->length();
    }

<<<<<<< HEAD
    const LowFuelAlert& __getitem__(size_t i) const
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
    const Button& __getitem__(size_t i) const
=======
    const LowFuelAlert& __getitem__(size_t i) const
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master
    {
        return (*self)[i];
    }
}


// Include the class interfaces
<<<<<<< HEAD
=======
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.i
%include "Button.h"

// Include the corresponding TopicDataType
%include "ButtonPubSubTypes.i"
=======
>>>>>>> master
%include "LowFuelAlert.h"

// Include the corresponding TopicDataType
%include "LowFuelAlertPubSubTypes.i"
<<<<<<< HEAD
=======
>>>>>>> master:Vehicle-Python/MessageFormats/LowFuelAlert/LowFuelAlert.i
>>>>>>> master
