# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

import fastdds
from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _MilesToRefuelWrapper
else:
    import _MilesToRefuelWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError(
                "You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MilesToRefuelWrapper.delete_SwigPyIterator

    def value(self):
        return _MilesToRefuelWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _MilesToRefuelWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _MilesToRefuelWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _MilesToRefuelWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _MilesToRefuelWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _MilesToRefuelWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _MilesToRefuelWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _MilesToRefuelWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _MilesToRefuelWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _MilesToRefuelWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _MilesToRefuelWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _MilesToRefuelWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _MilesToRefuelWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _MilesToRefuelWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _MilesToRefuelWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _MilesToRefuelWrapper.SwigPyIterator___sub__(self, *args)

    def __iter__(self):
        return self


# Register SwigPyIterator in _MilesToRefuelWrapper:
_MilesToRefuelWrapper.SwigPyIterator_swigregister(SwigPyIterator)


class _MilesToRefuelSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MilesToRefuelWrapper.delete__MilesToRefuelSeq


# Register _MilesToRefuelSeq in _MilesToRefuelWrapper:
_MilesToRefuelWrapper._MilesToRefuelSeq_swigregister(_MilesToRefuelSeq)


class MilesToRefuelSeq(_MilesToRefuelSeq):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MilesToRefuelWrapper.delete_MilesToRefuelSeq

    def __init__(self, *args):
        _MilesToRefuelWrapper.MilesToRefuelSeq_swiginit(
            self, _MilesToRefuelWrapper.new_MilesToRefuelSeq(*args))

    def __len__(self):
        return _MilesToRefuelWrapper.MilesToRefuelSeq___len__(self)

    def __getitem__(self, i):
        return _MilesToRefuelWrapper.MilesToRefuelSeq___getitem__(self, i)


# Register MilesToRefuelSeq in _MilesToRefuelWrapper:
_MilesToRefuelWrapper.MilesToRefuelSeq_swigregister(MilesToRefuelSeq)


class MilesToRefuel(object):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _MilesToRefuelWrapper.delete_MilesToRefuel

    def __init__(self, *args):
        _MilesToRefuelWrapper.MilesToRefuel_swiginit(
            self, _MilesToRefuelWrapper.new_MilesToRefuel(*args))

    def __eq__(self, x):
        return _MilesToRefuelWrapper.MilesToRefuel___eq__(self, x)

    def __ne__(self, x):
        return _MilesToRefuelWrapper.MilesToRefuel___ne__(self, x)

    def index(self, *args):
        return _MilesToRefuelWrapper.MilesToRefuel_index(self, *args)

    def milesToRefuel(self, *args):
        return _MilesToRefuelWrapper.MilesToRefuel_milesToRefuel(self, *args)

    @staticmethod
    def getMaxCdrSerializedSize(current_alignment=0):
        return _MilesToRefuelWrapper.MilesToRefuel_getMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def getCdrSerializedSize(data, current_alignment=0):
        return _MilesToRefuelWrapper.MilesToRefuel_getCdrSerializedSize(data, current_alignment)

    def serialize(self, cdr):
        return _MilesToRefuelWrapper.MilesToRefuel_serialize(self, cdr)

    def deserialize(self, cdr):
        return _MilesToRefuelWrapper.MilesToRefuel_deserialize(self, cdr)

    @staticmethod
    def getKeyMaxCdrSerializedSize(current_alignment=0):
        return _MilesToRefuelWrapper.MilesToRefuel_getKeyMaxCdrSerializedSize(current_alignment)

    @staticmethod
    def isKeyDefined():
        return _MilesToRefuelWrapper.MilesToRefuel_isKeyDefined()

    def serializeKey(self, cdr):
        return _MilesToRefuelWrapper.MilesToRefuel_serializeKey(self, cdr)


# Register MilesToRefuel in _MilesToRefuelWrapper:
_MilesToRefuelWrapper.MilesToRefuel_swigregister(MilesToRefuel)
GEN_API_VER = _MilesToRefuelWrapper.GEN_API_VER


class MilesToRefuelPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x,
                       v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _MilesToRefuelWrapper.MilesToRefuelPubSubType_swiginit(
            self, _MilesToRefuelWrapper.new_MilesToRefuelPubSubType())
    __swig_destroy__ = _MilesToRefuelWrapper.delete_MilesToRefuelPubSubType

    def serialize(self, data, payload):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_serialize(self, data, payload)

    def deserialize(self, payload, data):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, data):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_getSerializedSizeProvider(self, data)

    def getKey(self, data, ihandle, force_md5=False):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_createData(self)

    def deleteData(self, data):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_is_bounded(self)

    def is_plain(self):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_is_plain(self)

    def construct_sample(self, memory):
        return _MilesToRefuelWrapper.MilesToRefuelPubSubType_construct_sample(self, memory)
    m_md5 = property(_MilesToRefuelWrapper.MilesToRefuelPubSubType_m_md5_get,
                     _MilesToRefuelWrapper.MilesToRefuelPubSubType_m_md5_set)
    m_keyBuffer = property(_MilesToRefuelWrapper.MilesToRefuelPubSubType_m_keyBuffer_get,
                           _MilesToRefuelWrapper.MilesToRefuelPubSubType_m_keyBuffer_set)


# Register MilesToRefuelPubSubType in _MilesToRefuelWrapper:
_MilesToRefuelWrapper.MilesToRefuelPubSubType_swigregister(
    MilesToRefuelPubSubType)
