// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Miles.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Miles.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Miles::Miles()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7fac631b
    m_index = 0;
    // m_milesTraveled com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5b87ed94
    m_milesTraveled = 0.0;

}

Miles::~Miles()
{


}

Miles::Miles(
        const Miles& x)
{
    m_index = x.m_index;
    m_milesTraveled = x.m_milesTraveled;
}

Miles::Miles(
        Miles&& x)
{
    m_index = x.m_index;
    m_milesTraveled = x.m_milesTraveled;
}

Miles& Miles::operator =(
        const Miles& x)
{

    m_index = x.m_index;
    m_milesTraveled = x.m_milesTraveled;

    return *this;
}

Miles& Miles::operator =(
        Miles&& x)
{

    m_index = x.m_index;
    m_milesTraveled = x.m_milesTraveled;

    return *this;
}

bool Miles::operator ==(
        const Miles& x) const
{

    return (m_index == x.m_index && m_milesTraveled == x.m_milesTraveled);
}

bool Miles::operator !=(
        const Miles& x) const
{
    return !(*this == x);
}

size_t Miles::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t Miles::getCdrSerializedSize(
        const Miles& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void Miles::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_milesTraveled;

}

void Miles::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_milesTraveled;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void Miles::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t Miles::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& Miles::index()
{
    return m_index;
}

/*!
 * @brief This function sets a value in member milesTraveled
 * @param _milesTraveled New value for member milesTraveled
 */
void Miles::milesTraveled(
        double _milesTraveled)
{
    m_milesTraveled = _milesTraveled;
}

/*!
 * @brief This function returns the value of member milesTraveled
 * @return Value of member milesTraveled
 */
double Miles::milesTraveled() const
{
    return m_milesTraveled;
}

/*!
 * @brief This function returns a reference to member milesTraveled
 * @return Reference to member milesTraveled
 */
double& Miles::milesTraveled()
{
    return m_milesTraveled;
}


size_t Miles::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool Miles::isKeyDefined()
{
    return false;
}

void Miles::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
