// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Fuel.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Fuel.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Fuel::Fuel()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4f970963
    m_index = 0;
    // m_litersRemaining com.eprosima.idl.parser.typecode.PrimitiveTypeCode@61f8bee4
    m_litersRemaining = 0.0;
    // m_litersSpent com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7b49cea0
    m_litersSpent = 0.0;

}

Fuel::~Fuel()
{



}

Fuel::Fuel(
        const Fuel& x)
{
    m_index = x.m_index;
    m_litersRemaining = x.m_litersRemaining;
    m_litersSpent = x.m_litersSpent;
}

Fuel::Fuel(
        Fuel&& x)
{
    m_index = x.m_index;
    m_litersRemaining = x.m_litersRemaining;
    m_litersSpent = x.m_litersSpent;
}

Fuel& Fuel::operator =(
        const Fuel& x)
{

    m_index = x.m_index;
    m_litersRemaining = x.m_litersRemaining;
    m_litersSpent = x.m_litersSpent;

    return *this;
}

Fuel& Fuel::operator =(
        Fuel&& x)
{

    m_index = x.m_index;
    m_litersRemaining = x.m_litersRemaining;
    m_litersSpent = x.m_litersSpent;

    return *this;
}

bool Fuel::operator ==(
        const Fuel& x) const
{

    return (m_index == x.m_index && m_litersRemaining == x.m_litersRemaining && m_litersSpent == x.m_litersSpent);
}

bool Fuel::operator !=(
        const Fuel& x) const
{
    return !(*this == x);
}

size_t Fuel::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t Fuel::getCdrSerializedSize(
        const Fuel& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void Fuel::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_litersRemaining;
    scdr << m_litersSpent;

}

void Fuel::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_litersRemaining;
    dcdr >> m_litersSpent;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void Fuel::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t Fuel::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& Fuel::index()
{
    return m_index;
}

/*!
 * @brief This function sets a value in member litersRemaining
 * @param _litersRemaining New value for member litersRemaining
 */
void Fuel::litersRemaining(
        double _litersRemaining)
{
    m_litersRemaining = _litersRemaining;
}

/*!
 * @brief This function returns the value of member litersRemaining
 * @return Value of member litersRemaining
 */
double Fuel::litersRemaining() const
{
    return m_litersRemaining;
}

/*!
 * @brief This function returns a reference to member litersRemaining
 * @return Reference to member litersRemaining
 */
double& Fuel::litersRemaining()
{
    return m_litersRemaining;
}

/*!
 * @brief This function sets a value in member litersSpent
 * @param _litersSpent New value for member litersSpent
 */
void Fuel::litersSpent(
        double _litersSpent)
{
    m_litersSpent = _litersSpent;
}

/*!
 * @brief This function returns the value of member litersSpent
 * @return Value of member litersSpent
 */
double Fuel::litersSpent() const
{
    return m_litersSpent;
}

/*!
 * @brief This function returns a reference to member litersSpent
 * @return Reference to member litersSpent
 */
double& Fuel::litersSpent()
{
    return m_litersSpent;
}


size_t Fuel::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool Fuel::isKeyDefined()
{
    return false;
}

void Fuel::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
