// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MilesToRefuel.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MilesToRefuel.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

MilesToRefuel::MilesToRefuel()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@67205a84
    m_index = 0;
    // m_milesToRefuel com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7d0587f1
    m_milesToRefuel = 0.0;

}

MilesToRefuel::~MilesToRefuel()
{


}

MilesToRefuel::MilesToRefuel(
        const MilesToRefuel& x)
{
    m_index = x.m_index;
    m_milesToRefuel = x.m_milesToRefuel;
}

MilesToRefuel::MilesToRefuel(
        MilesToRefuel&& x)
{
    m_index = x.m_index;
    m_milesToRefuel = x.m_milesToRefuel;
}

MilesToRefuel& MilesToRefuel::operator =(
        const MilesToRefuel& x)
{

    m_index = x.m_index;
    m_milesToRefuel = x.m_milesToRefuel;

    return *this;
}

MilesToRefuel& MilesToRefuel::operator =(
        MilesToRefuel&& x)
{

    m_index = x.m_index;
    m_milesToRefuel = x.m_milesToRefuel;

    return *this;
}

bool MilesToRefuel::operator ==(
        const MilesToRefuel& x) const
{

    return (m_index == x.m_index && m_milesToRefuel == x.m_milesToRefuel);
}

bool MilesToRefuel::operator !=(
        const MilesToRefuel& x) const
{
    return !(*this == x);
}

size_t MilesToRefuel::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t MilesToRefuel::getCdrSerializedSize(
        const MilesToRefuel& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void MilesToRefuel::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_milesToRefuel;

}

void MilesToRefuel::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_milesToRefuel;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void MilesToRefuel::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t MilesToRefuel::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& MilesToRefuel::index()
{
    return m_index;
}

/*!
 * @brief This function sets a value in member milesToRefuel
 * @param _milesToRefuel New value for member milesToRefuel
 */
void MilesToRefuel::milesToRefuel(
        double _milesToRefuel)
{
    m_milesToRefuel = _milesToRefuel;
}

/*!
 * @brief This function returns the value of member milesToRefuel
 * @return Value of member milesToRefuel
 */
double MilesToRefuel::milesToRefuel() const
{
    return m_milesToRefuel;
}

/*!
 * @brief This function returns a reference to member milesToRefuel
 * @return Reference to member milesToRefuel
 */
double& MilesToRefuel::milesToRefuel()
{
    return m_milesToRefuel;
}


size_t MilesToRefuel::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool MilesToRefuel::isKeyDefined()
{
    return false;
}

void MilesToRefuel::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
