python_packages:
	ansible-playbook -i sleipnir.yml -u ansible install_packages.yml
python3.8:
	ansible-playbook -i sleipnir.yml -u ansible install_python3.8.yml
git2.27:
	ansible_playbook -i sleipnir.yml -u ansible install_git2.27.yml
