// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Trip.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_TRIP_H_
#define _FAST_DDS_GENERATED_TRIP_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Trip_SOURCE)
#define Trip_DllAPI __declspec( dllexport )
#else
#define Trip_DllAPI __declspec( dllimport )
#endif // Trip_SOURCE
#else
#define Trip_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Trip_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure Trip defined by the user in the IDL file.
 * @ingroup TRIP
 */
class Trip
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Trip();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Trip();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Trip that will be copied.
     */
    eProsima_user_DllExport Trip(
            const Trip& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Trip that will be copied.
     */
    eProsima_user_DllExport Trip(
            Trip&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Trip that will be copied.
     */
    eProsima_user_DllExport Trip& operator =(
            const Trip& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Trip that will be copied.
     */
    eProsima_user_DllExport Trip& operator =(
            Trip&& x);

    /*!
     * @brief Comparison operator.
     * @param x Trip object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Trip& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Trip object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Trip& x) const;

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();

    /*!
     * @brief This function sets a value in member miles
     * @param _miles New value for member miles
     */
    eProsima_user_DllExport void miles(
            double _miles);

    /*!
     * @brief This function returns the value of member miles
     * @return Value of member miles
     */
    eProsima_user_DllExport double miles() const;

    /*!
     * @brief This function returns a reference to member miles
     * @return Reference to member miles
     */
    eProsima_user_DllExport double& miles();

    /*!
     * @brief This function sets a value in member speed
     * @param _speed New value for member speed
     */
    eProsima_user_DllExport void speed(
            double _speed);

    /*!
     * @brief This function returns the value of member speed
     * @return Value of member speed
     */
    eProsima_user_DllExport double speed() const;

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport double& speed();

    /*!
     * @brief This function sets a value in member time
     * @param _time New value for member time
     */
    eProsima_user_DllExport void time(
            double _time);

    /*!
     * @brief This function returns the value of member time
     * @return Value of member time
     */
    eProsima_user_DllExport double time() const;

    /*!
     * @brief This function returns a reference to member time
     * @return Reference to member time
     */
    eProsima_user_DllExport double& time();

    /*!
     * @brief This function sets a value in member MPG
     * @param _MPG New value for member MPG
     */
    eProsima_user_DllExport void MPG(
            double _MPG);

    /*!
     * @brief This function returns the value of member MPG
     * @return Value of member MPG
     */
    eProsima_user_DllExport double MPG() const;

    /*!
     * @brief This function returns a reference to member MPG
     * @return Reference to member MPG
     */
    eProsima_user_DllExport double& MPG();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const Trip& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint32_t m_index;
    double m_miles;
    double m_speed;
    double m_time;
    double m_MPG;
};

#endif // _FAST_DDS_GENERATED_TRIP_H_