// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MpG.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MpG.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

MpG::MpG()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7fac631b
    m_index = 0;
    // m_mpg com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5b87ed94
    m_mpg = 0.0;

}

MpG::~MpG()
{


}

MpG::MpG(
        const MpG& x)
{
    m_index = x.m_index;
    m_mpg = x.m_mpg;
}

MpG::MpG(
        MpG&& x)
{
    m_index = x.m_index;
    m_mpg = x.m_mpg;
}

MpG& MpG::operator =(
        const MpG& x)
{

    m_index = x.m_index;
    m_mpg = x.m_mpg;

    return *this;
}

MpG& MpG::operator =(
        MpG&& x)
{

    m_index = x.m_index;
    m_mpg = x.m_mpg;

    return *this;
}

bool MpG::operator ==(
        const MpG& x) const
{

    return (m_index == x.m_index && m_mpg == x.m_mpg);
}

bool MpG::operator !=(
        const MpG& x) const
{
    return !(*this == x);
}

size_t MpG::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t MpG::getCdrSerializedSize(
        const MpG& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void MpG::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_mpg;

}

void MpG::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_mpg;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void MpG::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t MpG::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& MpG::index()
{
    return m_index;
}

/*!
 * @brief This function sets a value in member mpg
 * @param _mpg New value for member mpg
 */
void MpG::mpg(
        double _mpg)
{
    m_mpg = _mpg;
}

/*!
 * @brief This function returns the value of member mpg
 * @return Value of member mpg
 */
double MpG::mpg() const
{
    return m_mpg;
}

/*!
 * @brief This function returns a reference to member mpg
 * @return Reference to member mpg
 */
double& MpG::mpg()
{
    return m_mpg;
}


size_t MpG::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool MpG::isKeyDefined()
{
    return false;
}

void MpG::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
