// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
 * @file Button.cpp
=======
 * @file Move.cpp
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
#include "Button.h"
=======
#include "Move.h"
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
Button::Button()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7fac631b
    m_index = 0;
    // m_button com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5b87ed94
    m_button = 0;

}

Button::~Button()
=======
Move::Move()
{
    // m_ismoving com.eprosima.idl.parser.typecode.PrimitiveTypeCode@65e2dbf3
    m_ismoving = 0;
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@61f8bee4
    m_index = 0;

}

Move::~Move()
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{


}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
Button::Button(
        const Button& x)
=======
Move::Move(
        const Move& x)
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    m_ismoving = x.m_ismoving;
    m_index = x.m_index;
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
    m_button = x.m_button;
}

Button::Button(
        Button&& x)
=======
}

Move::Move(
        Move&& x)
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    m_ismoving = x.m_ismoving;
    m_index = x.m_index;
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
    m_button = x.m_button;
}

Button& Button::operator =(
        const Button& x)
=======
}

Move& Move::operator =(
        const Move& x)
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{

    m_ismoving = x.m_ismoving;
    m_index = x.m_index;
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
    m_button = x.m_button;
=======
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx

    return *this;
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
Button& Button::operator =(
        Button&& x)
=======
Move& Move::operator =(
        Move&& x)
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{

    m_ismoving = x.m_ismoving;
    m_index = x.m_index;
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
    m_button = x.m_button;
=======
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx

    return *this;
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
bool Button::operator ==(
        const Button& x) const
{

    return (m_index == x.m_index && m_button == x.m_button);
}

bool Button::operator !=(
        const Button& x) const
=======
bool Move::operator ==(
        const Move& x) const
{

    return (m_ismoving == x.m_ismoving && m_index == x.m_index);
}

bool Move::operator !=(
        const Move& x) const
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    return !(*this == x);
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
size_t Button::getMaxCdrSerializedSize(
=======
size_t Move::getMaxCdrSerializedSize(
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
size_t Button::getCdrSerializedSize(
        const Button& data,
=======
size_t Move::getCdrSerializedSize(
        const Move& data,
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
void Button::serialize(
=======
void Move::serialize(
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_ismoving;
    scdr << m_index;
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
    scdr << m_button;

}

void Button::deserialize(
=======

}

void Move::deserialize(
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_ismoving;
    dcdr >> m_index;
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
    dcdr >> m_button;
=======
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
}

/*!
 * @brief This function sets a value in member ismoving
 * @param _ismoving New value for member ismoving
 */
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
void Button::index(
        uint32_t _index)
=======
void Move::ismoving(
        uint32_t _ismoving)
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    m_ismoving = _ismoving;
}

/*!
 * @brief This function returns the value of member ismoving
 * @return Value of member ismoving
 */
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
uint32_t Button::index() const
=======
uint32_t Move::ismoving() const
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    return m_ismoving;
}

/*!
 * @brief This function returns a reference to member ismoving
 * @return Reference to member ismoving
 */
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
uint32_t& Button::index()
=======
uint32_t& Move::ismoving()
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    return m_ismoving;
}

/*!
<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
 * @brief This function sets a value in member button
 * @param _button New value for member button
 */
void Button::button(
        uint32_t _button)
{
    m_button = _button;
}

/*!
 * @brief This function returns the value of member button
 * @return Value of member button
 */
uint32_t Button::button() const
{
    return m_button;
}

/*!
 * @brief This function returns a reference to member button
 * @return Reference to member button
 */
uint32_t& Button::button()
{
    return m_button;
}


size_t Button::getKeyMaxCdrSerializedSize(
=======
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void Move::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t Move::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& Move::index()
{
    return m_index;
}


size_t Move::getKeyMaxCdrSerializedSize(
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
bool Button::isKeyDefined()
=======
bool Move::isKeyDefined()
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
{
    return false;
}

<<<<<<< HEAD:Vehicle-Python/MessageFormats/Button/Button.cxx
void Button::serializeKey(
=======
void Move::serializeKey(
>>>>>>> master:Vehicle-C++/Vehicle/src/Moving/Move.cxx
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
